version: '3.8'

services:
  frontend: 
    image: example-frontend
    environment: 
      - REACT_APP_BACKEND_URL=http://localhost:8080
    ports: 
      - 5000:5000
  backend: 
    image: example-backend
    environment: 
      - REQUEST_ORIGIN=http://localhost
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REDIS_HOST=redis
    ports: 
      - "8080:8080"
    depends_on: 
      - postgres
  redis:
    image: redis
  postgres: 
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend

# I added REQUEST_ORIGIN env to backend and ports to every service.