version: '3.8'

services:
  backend:
    image: example-backend
    container_name: server
    ports: 
      - 8080:8080
    environment:
    - REDIS_HOST=redis
    - POSTGRES_HOST=postgres
  frontend:
    image: example-frontend
    container_name: front
  redis:
    image: redis
    container_name: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  nginx.conf: