version: '3.8'

services:
  frontend:
    image: example-frontend
    container_name: example-frontend
    ports: 
      - 5000:5000
  backend:
    image: example-backend
    container_name: example-backend
    ports: 
      - 8080:8080
    environment:
    - REDIS_HOST=redis
    - POSTGRES_HOST=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DATABASE=postgres
  redis:
    image: redis
  postgres:
    image: postgres
    container_name: postgres-database